name: hydrogoal
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0' # Updated for compatibility

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

  liquid_swipe: ^3.1.0 

  flutter_animate: ^4.5.0
  
  google_fonts: ^6.2.1

  percent_indicator: ^4.2.3

  shared_preferences: ^2.2.3

  # Firebase Core Services
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.7

  # For picking images (Hydration Proof)
  image_picker: ^1.1.2
  camera: ^0.11.0          # For the desktop live preview
  camera_windows: ^0.2.1+1 # For Windows support

  # UI and Utility Packages
  table_calendar: ^3.1.1
  intl: ^0.19.0

  #For AI
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0

  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The "flutter" section is for Flutter-specific configurations.
# It is separate from the "dependencies" section above.
flutter:
  # This is the correct location for this line.
  uses-material-design: true
  assets:
    - .env