import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This was generated by flutterfire

// We will create this AuthWrapper screen in the next steps
// For now, we'll use a placeholder
// import 'package:hydro_goal/screens/auth/auth_wrapper.dart';

void main() async {
  // Ensure Flutter framework is ready before running the app
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the generated options file
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'HydroGoal', // Our new app name
      theme: ThemeData(
        primarySwatch: Colors.blue,
        scaffoldBackgroundColor: Colors.white,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      // We will replace this with our AuthWrapper soon.
      // For now, this placeholder shows that setup is complete.
      home: const SetupCompleteScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}

// A temporary screen to confirm everything is working
class SetupCompleteScreen extends StatelessWidget {
  const SetupCompleteScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.check_circle, color: Colors.green, size: 80),
            SizedBox(height: 20),
            Text(
              'Setup Complete!',
              style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 10),
            Text(
              'Project "HydroGoal" is ready.',
              style: TextStyle(fontSize: 16),
            ),
          ],
        ),
      ),
    );
  }
}
